# Generated by Django 5.0.6 on 2024-09-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('reusable', 'Reusable Products'), ('zero_waste', 'Zero-Waste Products'), ('home_garden', 'Home and Garden'), ('cleaning', 'Eco-friendly Cleaning Products'), ('office_school', 'Office & School')], max_length=20)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
