# Generated by Django 5.0.6 on 2024-09-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlasticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pet', 'PET (Polyethylene Terephthalate)'), ('hdpe', 'HDPE (High-Density Polyethylene)'), ('pvc', 'PVC (Polyvinyl Chloride)'), ('ldpe', 'LDPE (Low-Density Polyethylene)'), ('pp', 'PP (Polypropylene)'), ('ps', 'PS (Polystyrene)'), ('other', 'Other Plastics')], max_length=20)),
                ('basic_quantity', models.FloatField(help_text='Basic quantity in kilograms or appropriate units')),
                ('supercoins_for_basic_quantity', models.FloatField(help_text='Supercoins awarded for the basic quantity')),
                ('plastic_image', models.ImageField(blank=True, null=True, upload_to='plastic_items')),
            ],
        ),
    ]
